# Generated by Django 3.2.6 on 2022-03-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=' ', upload_to='img'),
            preserve_default=False,
        ),
    ]
