# Generated by Django 3.2.6 on 2022-03-26 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.URLField(blank=True, null=True),
        ),
    ]
