# Generated by Django 3.2.6 on 2022-03-26 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0002_alter_blog_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='cover',
            new_name='Imgagr_URL',
        ),
    ]
