# Generated by Django 3.2.6 on 2022-03-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0003_blog_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='user_name',
        ),
    ]
