# Generated by Django 3.2.6 on 2022-03-26 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0003_rename_cover_blog_imgagr_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Imgagr_URL',
            new_name='Image_URL',
        ),
    ]
