# Generated by Django 3.2.6 on 2022-03-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0011_remove_blog_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='media/img'),
            preserve_default=False,
        ),
    ]
