# Generated by Django 3.2.6 on 2022-03-22 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0012_blog_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='image',
        ),
    ]
