# Generated by Django 3.2.6 on 2022-03-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0013_remove_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
