# Generated by Django 3.2.6 on 2022-03-22 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0014_blog_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Img',
            new_name='Imge',
        ),
    ]
