# Generated by Django 3.2.6 on 2022-03-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0015_rename_img_blog_imge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='Imge',
        ),
    ]
