# Generated by Django 3.2.6 on 2022-03-23 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myBlog', '0016_remove_blog_imge'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
